-- MySQL Script generated by MySQL Workbench
-- Thursday 24 May 2022 09:53:22 AM
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema `AttendanceMaster`
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema `AttendanceMaster`
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AttendanceMaster`;
USE `AttendanceMaster`;

-- -----------------------------------------------------
-- Table `AttendanceMaster`.`Attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AttendanceMaster`.`Attendance` (
`student_id` VARCHAR(100) NOT NULL ,
`student_name` VARCHAR(100) NOT NULL,
`student_mobile` BIGINT NOT NULL,
`student_emailid` VARCHAR(200) NOT NULL,
`Attendance_Status` INT NOT NULL DEFAULT(0),
`Attendance_Date` datetime DEFAULT(NOW()),
PRIMARY KEY (`student_id`))

ENGINE = InnoDB;